/**
 * RSI parity against MetaTrader's OWN output.
 *
 * The fixture is not synthetic and not generated by this codebase. It was
 * produced inside MetaTrader by `MQL5/Scripts/RsiReference.mq5`, which calls
 * `iRSI(XAUUSD, PERIOD_M1, 5, PRICE_CLOSE)` and writes the terminal's values
 * next to the bars they were computed from. That indirection exists because
 * the MetaTrader5 Python API exposes no indicator functions — there is no
 * `iRSI` to call from outside the terminal.
 *
 * So this is a comparison against the terminal, not against a second
 * implementation of the same formula, which is what makes it worth keeping as
 * a regression test rather than as a one-off check.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { commitClosedBar, createRsiState, currentRsi, projectRsi, rsiFromAverages } from '../../src/xauusd-rsi/rsi';
import { SPEC } from '../../src/xauusd-rsi/spec';

interface Row {
  timeSec: number;
  close: number;
  mt5Rsi: number;
}

function loadFixture(): Row[] {
  const text = readFileSync(join(__dirname, 'fixtures', 'mt5-rsi-reference.csv'), 'utf8');
  return text
    .split(/\r?\n/)
    .filter((l) => l.trim().length > 0)
    .slice(1)
    .map((line) => {
      const p = line.split(',');
      return { timeSec: Number(p[0]), close: Number(p[4]), mt5Rsi: Number(p[5]) };
    });
}

/**
 * Bars before this index are excluded from the parity assertion.
 *
 * The fixture starts mid-history: the terminal's buffer had been folding this
 * symbol's entire loaded history, while a fresh state here seeds from the
 * fixture's first bar. Wilder's recursive average converges, so the two agree
 * after a few hundred bars — the early gap is expected arithmetic, not
 * disagreement, and is asserted to CLOSE rather than quietly skipped.
 */
const CONVERGED_FROM = 300;

describe('RSI parity with MetaTrader 5', () => {
  const rows = loadFixture();

  function computeSeries(): Array<number | null> {
    let state = createRsiState(SPEC.rsi.period);
    return rows.map((r) => {
      state = commitClosedBar(state, r.close);
      return currentRsi(state);
    });
  }

  it('has a usable fixture', () => {
    expect(rows.length).toBeGreaterThan(1_000);
    expect(rows.every((r) => Number.isFinite(r.close) && Number.isFinite(r.mt5Rsi))).toBe(true);
  });

  it("matches the terminal's own iRSI to floating-point precision once converged", () => {
    const mine = computeSeries();
    let maxDiff = 0;
    let compared = 0;
    for (let i = CONVERGED_FROM; i < rows.length; i += 1) {
      const value = mine[i];
      if (value === null) continue;
      compared += 1;
      maxDiff = Math.max(maxDiff, Math.abs(value - rows[i].mt5Rsi));
    }
    expect(compared).toBeGreaterThan(800);
    // Verified at 5e-11 against 5,000 live bars when this was first run.
    expect(maxDiff).toBeLessThan(1e-6);
  });

  it('converges toward the terminal rather than drifting away from it', () => {
    // Guards the exclusion above: if the early gap did NOT close, excluding
    // early bars would be hiding a real defect instead of an artefact of
    // where the fixture starts.
    const mine = computeSeries();
    const diffAt = (i: number) => Math.abs((mine[i] ?? 0) - rows[i].mt5Rsi);
    const early = Math.max(diffAt(10), diffAt(20), diffAt(30));
    const late = Math.max(diffAt(rows.length - 3), diffAt(rows.length - 2), diffAt(rows.length - 1));
    expect(late).toBeLessThan(early);
    expect(late).toBeLessThan(1e-6);
  });

  it('projects a forming bar to exactly the value that price produces on close', () => {
    let state = createRsiState(SPEC.rsi.period);
    for (const r of rows.slice(0, 400)) state = commitClosedBar(state, r.close);

    const nextClose = rows[400].close;
    const projected = projectRsi(state, nextClose);
    const committed = currentRsi(commitClosedBar(state, nextClose));

    expect(projected).toBe(committed);
    expect(Math.abs((projected as number) - rows[400].mt5Rsi)).toBeLessThan(1e-6);
  });

  it('leaves committed state untouched when projecting, at any price', () => {
    let state = createRsiState(SPEC.rsi.period);
    for (const r of rows.slice(0, 400)) state = commitClosedBar(state, r.close);
    const snapshot = JSON.stringify(state);

    projectRsi(state, 1);
    projectRsi(state, 99_999);
    projectRsi(state, rows[400].close);

    expect(JSON.stringify(state)).toBe(snapshot);
  });
});

describe("MT5's zero-loss convention, and what it actually implies", () => {
  it('reports 100 when average loss is zero, matching RSI.mq5', () => {
    expect(rsiFromAverages(1, 0)).toBe(100);
    expect(rsiFromAverages(0, 0)).toBe(100);
  });

  it('a history with NO downward change at all reads 100 after flat closes', () => {
    let s = createRsiState(5);
    for (const c of [1990, 1992, 1994, 1996, 1998, 2000, 2000, 2000, 2000, 2000]) s = commitClosedBar(s, c);
    expect(currentRsi(s)).toBe(100);
  });

  it('but a MIXED history does NOT reach 100 on five flat closes', () => {
    // This is the case that matters in practice and it narrows the concern
    // considerably: Wilder's average loss decays geometrically but never
    // reaches zero, so once any down move exists in the smoothed history,
    // flat closes raise RSI without pinning it to the extreme.
    let s = createRsiState(5);
    for (const c of [2000, 2004, 1998, 2003, 1999, 2002, 2002, 2002, 2002, 2002]) s = commitClosedBar(s, c);
    const value = currentRsi(s) as number;
    expect(value).toBeGreaterThan(50);
    expect(value).toBeLessThan(60);
    expect(value).not.toBe(100);
  });

  it('a falling history then flat closes reads 0, the mirror case', () => {
    let s = createRsiState(5);
    for (const c of [2010, 2008, 2006, 2004, 2002, 2000, 2000, 2000, 2000, 2000]) s = commitClosedBar(s, c);
    expect(currentRsi(s)).toBe(0);
  });

  it('real XAUUSD M1 data contains no flat run long enough to zero the average loss', () => {
    // Recorded as evidence for the disclosure, not as a guarantee about
    // future data: across this sample the longest run of unchanged closes is
    // shorter than the RSI period, so the pinned-to-100 case did not arise.
    const rows = loadFixture();
    let longest = 1;
    let run = 1;
    for (let i = 1; i < rows.length; i += 1) {
      run = rows[i].close === rows[i - 1].close ? run + 1 : 1;
      longest = Math.max(longest, run);
    }
    expect(longest).toBeLessThan(SPEC.rsi.period);
  });
});
