import { api, type RetestBucket, type RetestPaperSummary } from "@/lib/api";
import { PageHeader } from "@/components/PageHeader";
import { StatusPill } from "@/components/StatusPill";
import { Tile } from "@/components/Tile";
import { EmptyState } from "@/components/EmptyState";

// Research artifacts are regenerated by CLI runs; always read the latest files.
export const dynamic = "force-dynamic";

const pct = (x: number | null | undefined) => (x === null || x === undefined ? "n/a" : `${(x * 100).toFixed(1)}%`);
// Zero trades is not a 0% win rate — it is no sample at all. Only the resolved-count cell decides this;
// counts (WIN/LOSS/etc.) are shown regardless so "0" is still visible where it is genuinely zero.
const winRateCell = (numerator: number, denominator: number, rate: number | null) =>
  denominator === 0 ? "No sample" : `${numerator}/${denominator} (${pct(rate)})`;
const range = (r: [number, number] | null, money = false) => {
  if (!r) return "n/a";
  const f = (x: number) => (money ? `$${x.toFixed(2)}` : `${+x.toFixed(2)}`);
  return r[0] === r[1] ? f(r[0]) : `${f(r[0])} … ${f(r[1])}`;
};
const json = (x: unknown) => (x && typeof x === "object" && Object.keys(x).length ? JSON.stringify(x) : "none");

function BucketRow({ label, b }: { label: string; b: RetestBucket }) {
  const ci = b.resolvedWinRate.wilson95;
  return (
    <tr className="border-t border-border">
      <td className="py-1.5 pr-3">{label}</td>
      <td className="font-mono">{b.eligibleEvents}</td>
      <td className="font-mono">{b.counts.WIN}</td>
      <td className="font-mono">{b.counts.LOSS}</td>
      <td className="font-mono">{b.counts.AMBIGUOUS}</td>
      <td className="font-mono">{b.counts.INDETERMINATE}</td>
      <td className="font-mono">{b.counts.UNRESOLVED}</td>
      <td className="font-mono">{winRateCell(b.resolvedWinRate.numerator, b.resolvedWinRate.denominator, b.resolvedWinRate.rate)}</td>
      <td className="font-mono">{b.resolvedWinRate.denominator === 0 ? "—" : ci ? `${pct(ci[0])}–${pct(ci[1])}` : "n/a"}</td>
      <td className="font-mono">{b.eligibleEvents === 0 ? "—" : `${pct(b.allEligibleBounds.low)} – ${pct(b.allEligibleBounds.high)}`}</td>
    </tr>
  );
}

function PaperRow({ s }: { s: RetestPaperSummary }) {
  return (
    <tr className="border-t border-border align-top">
      <td className="py-1.5 pr-3 font-mono text-xs">{s.balanceId}</td>
      <td className="font-mono text-xs">{s.costId}</td>
      <td className="font-mono">{s.branches}{s.branchCapHit ? " (cap)" : ""}</td>
      <td className="font-mono">{range(s.tradesEntered)}</td>
      <td className="font-mono">{range(s.netPnlUsd, true)}</td>
      <td className="font-mono">{range(s.netExpectancyUsdPerTrade, true)}</td>
      <td className="font-mono">{range(s.profitFactor)}</td>
      <td className="font-mono">{range(s.maxEquityDrawdownUsd, true)}</td>
      <td className="font-mono">{range(s.exposurePct)}</td>
      <td className="text-xs">{Object.entries(s.decisionTally).map(([k, r]) => `${k}: ${range(r)}`).join(", ") || "no study events"}</td>
    </tr>
  );
}

export default async function GoldRetestResearchPage() {
  const data = await api.goldRetestResearch();
  const run = data.run;

  return (
    <div className="flex flex-col gap-6">
      <PageHeader title="Gold H4 confirmed-retest research" right={<StatusPill status="NO ORDERS" />} />

      <div className="rounded-lg border border-border bg-surface px-4 py-3.5 text-sm flex flex-col gap-1">
        <p><span className="text-text-muted">Version</span> <span className="font-mono">{data.strategyVersion}</span></p>
        <p><span className="text-text-muted">Spec hash</span> <span className="font-mono text-xs break-all">{data.currentSpecHash}</span></p>
        <p><span className="text-text-muted">Execution</span> {data.executionBoundary}</p>
        <p className="text-xs text-text-muted">Fixed research assumptions — not a claim of profitability. Rules partly completed by GPT from the friend&apos;s principles; not an exact reproduction of discretionary trading.</p>
        <p className="text-xs text-text-muted font-medium">This page shows research replay and collection status only. A recent quote or a fresh chart below means data is arriving — it does not mean this strategy is profitable, validated, or running live in any account.</p>
      </div>

      {!run ? (
        <EmptyState>No historical run found. Run <code>npm run confirmed-retest:study</code> in backend/.</EmptyState>
      ) : (
        <>
          {!run.specHashMatchesCurrent && (
            <div className="rounded-lg border border-down bg-down-soft px-4 py-3 text-sm text-down">Latest run was produced under a different spec hash — do not compare with the current rules.</div>
          )}

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Tile label="Conclusion" value={run.manifest.conclusion.conclusion.replace(/_/g, " ")} tone="warn" />
            <Tile label="Frozen end (UTC)" value={run.manifest.frozenEndUtc.slice(0, 16)} />
            <Tile label="Levels activated" value={String((run.formation.levelsActivated.RESISTANCE ?? 0) + (run.formation.levelsActivated.SUPPORT ?? 0))} />
            <Tile label="Eligible events" value={String(run.eventStudy.full.eligibleEvents)} />
          </div>
          <p className="text-sm">{run.manifest.conclusion.reason}.</p>
          <p className="text-xs text-text-muted font-mono break-all">run {run.runId} · data {run.manifest.dataHash} · {run.manifest.runCommand} · git {run.manifest.gitCommit.slice(0, 10)}</p>

          <section className="rounded-lg border border-border bg-surface px-4 py-3.5">
            <h2 className="text-sm font-medium mb-2">Why levels did or did not form</h2>
            <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1 text-xs">
              <div><dt className="text-text-muted inline">H4 bars replayed: </dt><dd className="inline font-mono">{run.formation.h4BarsProcessed}</dd></div>
              <div><dt className="text-text-muted inline">Pivot candidates R/S: </dt><dd className="inline font-mono">{run.formation.pivotCandidates.RESISTANCE}/{run.formation.pivotCandidates.SUPPORT}</dd></div>
              <div><dt className="text-text-muted inline">Qualified ($10 rejection) R/S: </dt><dd className="inline font-mono">{run.formation.qualifiedPivots.RESISTANCE}/{run.formation.qualifiedPivots.SUPPORT}</dd></div>
              <div><dt className="text-text-muted inline">Rejected, no $10 close R/S: </dt><dd className="inline font-mono">{run.formation.rejectedNoRejectionClose.RESISTANCE}/{run.formation.rejectedNoRejectionClose.SUPPORT}</dd></div>
              <div><dt className="text-text-muted inline">Exact-price repeats, any distance R/S: </dt><dd className="inline font-mono">{run.formation.exactPriceRepeatPairsAnyDistance.RESISTANCE}/{run.formation.exactPriceRepeatPairsAnyDistance.SUPPORT}</dd></div>
              <div><dt className="text-text-muted inline">Exact-price repeats, 5–120 bars R/S: </dt><dd className="inline font-mono">{run.formation.exactPriceRepeatPairsInDistanceWindow.RESISTANCE}/{run.formation.exactPriceRepeatPairsInDistanceWindow.SUPPORT}</dd></div>
              <div><dt className="text-text-muted inline">Pair rejection reasons: </dt><dd className="inline font-mono">{json(run.formation.pairOutcomes)}</dd></div>
              <div><dt className="text-text-muted inline">Activations blocked: </dt><dd className="inline font-mono">{json(run.formation.activationsBlocked)}</dd></div>
            </dl>
          </section>

          <section className="rounded-lg border border-border bg-surface px-4 py-3.5 overflow-x-auto">
            <h2 className="text-sm font-medium mb-1">Output A — event study (overlap allowed; not account performance)</h2>
            <p className="text-xs text-text-muted mb-2">First returns by kind: {json(run.eventStudy.studyEventsByKind)} · not eligible (each with its reason): {json(run.eventStudy.ineligibleByReason)}</p>
            <table className="w-full text-xs">
              <thead className="text-text-muted text-left"><tr><th>Bucket</th><th>N</th><th>W</th><th>L</th><th>Amb.</th><th>Indet.</th><th>Unres.</th><th>W/(W+L)</th><th>Wilson 95%</th><th>W/N – (N−L)/N</th></tr></thead>
              <tbody>
                <BucketRow label="Full period" b={run.eventStudy.full} />
                <BucketRow label="BUY (support)" b={run.eventStudy.byDirection.BUY} />
                <BucketRow label="SELL (resistance)" b={run.eventStudy.byDirection.SELL} />
                {Object.entries(run.eventStudy.byYear).map(([k, b]) => <BucketRow key={k} label={k} b={b} />)}
                {Object.entries(run.eventStudy.byHalfYear).map(([k, b]) => <BucketRow key={k} label={k} b={b} />)}
              </tbody>
            </table>
            <p className="text-xs text-text-muted mt-2">{run.eventStudy.dependence.note}</p>
          </section>

          <section className="rounded-lg border border-border bg-surface px-4 py-3.5 overflow-x-auto">
            <h2 className="text-sm font-medium mb-1">Output B — one-position paper simulation (skip reasons per scenario)</h2>
            <p className="text-xs text-text-muted mb-2">$1,000 is an assumed balance (no demo equity snapshot exists for this account); $10,000 is a pre-declared sensitivity only. All costs are labeled assumptions, not observed history.</p>
            <div className="rounded-md border border-warn/40 bg-warn-soft/40 px-3 py-2 text-xs mb-3">
              <span className="font-medium">Why the $1,000 scenario would block every entry: </span>
              at the frozen 0.01 lot and 100 oz/lot contract, a $10 stop risks $10.00 — 1% of $1,000, above the frozen 0.5% stop-risk cap.
              The minimum equity that clears that cap at this fixed volume is <span className="font-mono">$2,000</span>; volume and risk caps are not changed here.
            </div>
            <table className="w-full text-xs">
              <thead className="text-text-muted text-left"><tr><th>Balance</th><th>Costs</th><th>Branches</th><th>Trades</th><th>Net P&amp;L</th><th>Exp./trade</th><th>PF</th><th>Max DD</th><th>Exposure %</th><th>Decisions (incl. skips)</th></tr></thead>
              <tbody>{run.paper.map((p) => <PaperRow key={`${p.summary.balanceId}-${p.summary.costId}`} s={p.summary} />)}</tbody>
            </table>
          </section>

          <section className="rounded-lg border border-border bg-surface px-4 py-3.5 overflow-x-auto">
            <h2 className="text-sm font-medium mb-2">Every first return and its decision</h2>
            {run.events.length === 0 ? (
              <EmptyState>No level ever activated, so no first return, entry or skip exists to list.</EmptyState>
            ) : (
              <table className="w-full text-xs">
                <thead className="text-text-muted text-left"><tr><th>Touch interval (UTC)</th><th>Level</th><th>Kind</th><th>Eligible / reason</th><th>Outcome</th><th>Paper ($1k gross)</th><th>Paper ($10k base)</th></tr></thead>
                <tbody>
                  {run.events.map((e) => (
                    <tr key={String(e.id)} className="border-t border-border align-top">
                      <td className="py-1 font-mono">{String(e.touchIntervalStartUtc).slice(0, 16)}</td>
                      <td className="font-mono">{String(e.role)} {String(e.levelPrice)}</td>
                      <td>{String(e.kind)}</td>
                      <td>{e.eligible ? "eligible" : String(e.ineligibleReason)}</td>
                      <td>{String(e.status ?? "—")}</td>
                      <td className="font-mono">{json(e.paperPrimaryGross)}</td>
                      <td className="font-mono">{json(e.paperSensitivityBase)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </section>

          <section className="rounded-lg border border-border bg-surface px-4 py-3.5 overflow-x-auto">
            <h2 className="text-sm font-medium mb-2">Data coverage and evidence</h2>
            <table className="w-full text-xs mb-3">
              <thead className="text-text-muted text-left"><tr><th>TF</th><th>Rows</th><th>First (UTC)</th><th>Last (UTC)</th><th>Non-cent</th><th>OHLC</th><th>Grid</th><th>Weekend</th><th>TZ</th></tr></thead>
              <tbody>
                {run.coverage.validations.map((v) => (
                  <tr key={v.timeframe} className="border-t border-border">
                    <td className="py-1">{v.timeframe}</td><td className="font-mono">{v.rows}</td><td className="font-mono">{v.firstUtc?.slice(0, 16)}</td><td className="font-mono">{v.lastUtc?.slice(0, 16)}</td>
                    <td className="font-mono">{v.nonCentPrices}</td><td className="font-mono">{v.ohlcViolations}</td><td className="font-mono">{v.gridMisaligned}</td><td className="font-mono">{v.weekendServerBars}</td><td className="font-mono">{v.timezoneConversionErrors}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="text-xs">M1 gaps: {Object.entries(run.coverage.m1Gaps.byKind).map(([k, x]) => `${k} ${x.count} (${x.missingMinutes} min)`).join(" · ")} · M5 bars substituted: {run.coverage.substitutedM5Bars} · H4 vs M1 aggregate: {run.coverage.h4VsM1.exactMatch}/{run.coverage.h4VsM1.h4BarsChecked} exact</p>
            <p className="text-xs text-text-muted mt-1">Stored ticks {run.coverage.provenance.storedTicks} · account snapshots {run.coverage.provenance.accountSnapshots} · {run.coverage.provenance.backfillLogInstrumentVerification}</p>
            <details className="mt-2 text-xs">
              <summary className="cursor-pointer text-text-muted">{run.coverage.m1Gaps.unconfirmedList.length} unconfirmed M1 gaps</summary>
              <ul className="font-mono mt-1">{run.coverage.m1Gaps.unconfirmedList.map((g) => <li key={g.id}>{g.startUtc.slice(0, 16)} {g.minutes}m {g.kind}{g.bridge ? ` bridge ${g.bridge}` : ""}</li>)}</ul>
            </details>
          </section>
        </>
      )}

      <section className="rounded-lg border border-border bg-surface px-4 py-3.5">
        <h2 className="text-sm font-medium mb-2">Collector &amp; watch-only status (live observations)</h2>
        {!data.watch ? (
          <p className="text-xs text-text-muted">The watcher has not written a status yet. Start it with <code>npm run confirmed-retest:watch</code> (one cycle) or <code>npm run confirmed-retest:watcher</code> (persistent).</p>
        ) : (
          <div className="text-xs flex flex-col gap-3">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              <Tile label="Order execution" value={data.watch.orderExecution} tone="ok" />
              <Tile label="Watcher evaluation" value={data.watch.evaluation.status.replace(/_/g, " ")} tone={data.watch.evaluation.status === "EVALUATED_NEW_DATA" || data.watch.evaluation.status === "WAITING_FOR_NEW_COMPLETED_DATA" ? "ok" : "warn"} />
              <Tile label="Timestamp verification" value={data.watch.timestampVerification.recorded.status} tone={data.watch.timestampVerification.live.status === "LIVE_CONTRADICTED" ? "down" : "ok"} />
              <Tile label="Collector" value={data.watch.collector ? (data.watch.collector.mt5Connected ? `connected, ${data.watch.collector.ageSeconds}s ago` : "MT5 disconnected") : "no heartbeat seen"} tone={data.watch.collector?.mt5Connected ? "ok" : "warn"} />
            </div>

            <p>{data.watch.evaluation.reason}</p>

            <div className="rounded-md border border-border px-3 py-2">
              <p className="font-medium mb-1">Timestamp basis</p>
              <p>Recorded: {data.watch.timestampVerification.recorded.interpretation} — verified {data.watch.timestampVerification.recorded.verifiedOn}.</p>
              <p className={data.watch.timestampVerification.live.status === "LIVE_CONTRADICTED" ? "text-down font-medium" : "text-text-muted"}>
                Live re-check just now: {data.watch.timestampVerification.live.status.replace(/_/g, " ")} — {data.watch.timestampVerification.live.detail}
              </p>
              {data.watch.timestampVerification.live.status === "LIVE_CONTRADICTED" && (
                <p className="text-down">Session-dependent evaluation is blocked until this is resolved. Raw data collection is unaffected.</p>
              )}
            </div>

            <div className="rounded-md border border-border px-3 py-2">
              <p className="font-medium mb-1">Last available data (with timezone)</p>
              <p className={data.watch.goldData.stale ? "text-warn" : ""}>
                Latest stored XAUUSD M1 close: <span className="font-mono">{data.watch.goldData.latestStoredM1CloseUtc ?? "none"} UTC</span>
                {data.watch.goldData.latestStoredM1AgeSeconds !== null && ` (${Math.round(data.watch.goldData.latestStoredM1AgeSeconds / 60)} min ago${data.watch.goldData.stale ? ", stale" : ""})`}
              </p>
              <p className="text-text-muted">{data.watch.goldData.note}</p>
              {data.watch.quotes.map((q) => (
                <p key={q.symbol} className="font-mono">
                  {q.symbol}: bid {q.bid} / ask {q.ask} (spread {q.spread}) · quote time {q.tickAtUtc} UTC · received {q.receiptAgeSeconds}s ago
                </p>
              ))}
              {data.watch.quotes.length === 0 && <p className="text-text-muted">No live quote received yet for any symbol.</p>}
            </div>

            <p>Settled through {data.watch.settledEndUtc ?? "—"} · volume {data.watch.volumeLots} lot (user-set only; {data.watch.volumeAudit.length} change{data.watch.volumeAudit.length === 1 ? "" : "s"} logged)</p>
            <p>
              Active levels {data.watch.activeLevels.length} · forward first returns {data.watch.counts.forwardEvents} · pending outcomes {data.watch.counts.pendingOutcomes}
              {data.watch.counts.forwardEvents === 0 && " — zero forward events is not zero performance: no level has formed to produce one (see “Why levels did or did not form” above)."}
            </p>
            {data.watch.watcher && (
              <p className="text-text-muted">Watcher pid {data.watch.watcher.pid}, cycle {data.watch.watcher.cycle}, started {data.watch.watcher.startedAtUtc}{data.watch.watcher.loop ? `, next cycle ~${data.watch.watcher.nextCycleAtUtc}` : " (single cycle, not currently looping)"}{data.watch.watcher.consecutiveErrors > 0 ? ` — ${data.watch.watcher.consecutiveErrors} consecutive errors` : ""}.</p>
            )}
            {Object.keys(data.watch.quoteGate).length > 0 && (
              <div>
                <p className="font-medium">Shadow entry gate decisions</p>
                {Object.values(data.watch.quoteGate).map((g, i) => <p key={i} className="font-mono">{g.decidedAtUtc}: {g.pass ? "shadow entry allowed" : `skipped: ${g.reason}`}</p>)}
              </div>
            )}
          </div>
        )}
      </section>
    </div>
  );
}
